name: Tests

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["8.4"]
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values: post_max_size=256M, max_execution_time=180
          coverage: xdebug
          tools: phpunit

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php-versions }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Test with PHPUnit
        run: vendor/bin/phpunit --coverage-clover coverage/clover.xml --coverage-text

      - name: "Upload coverage results to Coveralls"
        if: ${{ success() }}
        uses: coverallsapp/github-action@v2
        with:
          format: clover
          file: coverage/clover.xml
          flag-name: ${{ matrix.os }}-php-${{ matrix.php }}
          parallel: true

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
